"""
ReferenceRegistry -- the single place the pipeline asks for reference data.

Loading strategy, in priority order:

  1. **Official** Unilog reference workbooks in ``data/reference/`` (or wherever
     ``settings.reference_dir`` points).  Filenames are matched by pattern, not
     hard-coded, so ``UniCat_Manufacturer_and_Brand_List.xlsx``,
     ``UniCat Manufacturer & Brand List (v2).xlsx`` etc. all resolve.
  2. **Derived** masters mined from the working data actually being processed.
  3. **Seed** packs shipped in ``data/packs/`` (UOM abbreviations, brand lexicon,
     taxonomy templates).
  4. **Computed** tables (decimal<->fraction) generated by exact arithmetic.

Every consumer can read ``registry.stats.sources`` to see which tier is live, so
the UI never presents a derived mapping as if it were official master data.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from backend.normalization import fractions as fx
from backend.normalization.uom import UomEntry, UomRegistry, set_default_registry
from backend.reference import loader
from backend.reference.bootstrap import (
    DISTRIBUTOR_BRAND_FANOUT, MinedMasters, match_key, mine_masters, split_name_code,
)
from backend.reference.brand_lexicon import BrandLexicon, LexiconEntry
from backend.reference.schema import (
    PROVENANCE_COMPUTED, PROVENANCE_DERIVED, PROVENANCE_OFFICIAL, PROVENANCE_SEED,
    BrandRecord, LeafNode, LovAttribute, LovValue, ManufacturerRecord, ReferenceStats,
)
from backend.reference.taxonomy import Taxonomy

# Filename patterns for the official reference pack.  Matched case-insensitively
# against the file *stem* so version suffixes and spacing variants still resolve.
OFFICIAL_PATTERNS: Dict[str, str] = {
    "manufacturer_brand": r"unicat.*(manufacturer|brand)|manufacturer.*brand.*list",
    "lov": r"unicat.*lov|lov.*v\d|controlled.*vocab",
    "uom": r"uom.*standard|master.*uom|abbreviation.*terms",
    "fractions": r"decimal.*fraction|fraction.*decimal",
    "faucets": r"faucet",
    "fittings": r"fitting",
    "guidelines": r"content.*guideline|internal.*content",
    "summary": r"reference.*document.*summary",
}


def discover_reference_files(directory: Path) -> Dict[str, Path]:
    """Map logical reference names to whichever files are actually present."""
    found: Dict[str, Path] = {}
    if not directory.exists():
        return found
    for path in sorted(directory.iterdir()):
        if not path.is_file() or path.suffix.lower() not in (".xlsx", ".xlsm", ".csv", ".docx"):
            continue
        stem = path.stem.lower()
        for key, pattern in OFFICIAL_PATTERNS.items():
            if key not in found and re.search(pattern, stem):
                found[key] = path
                break
    return found


@dataclass
class ReferenceRegistry:
    """Aggregated reference data with provenance tracking."""

    manufacturers: List[ManufacturerRecord] = field(default_factory=list)
    brands: List[BrandRecord] = field(default_factory=list)
    taxonomy: Optional[Taxonomy] = None
    uom: Optional[UomRegistry] = None
    brand_lexicon: Optional[BrandLexicon] = None
    guideline_blocks: List[Dict[str, str]] = field(default_factory=list)
    stats: ReferenceStats = field(default_factory=ReferenceStats)

    # Lookup indexes, rebuilt by ``reindex``.
    _manuf_by_key: Dict[str, ManufacturerRecord] = field(default_factory=dict, repr=False)
    _manuf_by_code: Dict[str, ManufacturerRecord] = field(default_factory=dict, repr=False)
    _brand_by_key: Dict[str, BrandRecord] = field(default_factory=dict, repr=False)

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------
    @classmethod
    def build(cls, reference_dir: Path, pack_dir: Path,
              working_rows: Optional[Sequence[Dict[str, object]]] = None) -> "ReferenceRegistry":
        reg = cls()
        stats = reg.stats
        official = discover_reference_files(Path(reference_dir))

        # -- 1. UOM standards ------------------------------------------
        uom_entries, uom_source = cls._load_uom(official.get("uom"))
        if uom_entries:
            reg.uom = UomRegistry(uom_entries, provenance=PROVENANCE_OFFICIAL)
            stats.sources["uom"] = f"{PROVENANCE_OFFICIAL}:{uom_source}"
        else:
            reg.uom = UomRegistry(provenance=PROVENANCE_SEED)
            stats.sources["uom"] = f"{PROVENANCE_SEED}:packaged abbreviation table"
        set_default_registry(reg.uom)
        stats.uom_entries = len(reg.uom)

        # -- 2. Decimal/fraction table ---------------------------------
        overrides, frac_source = cls._load_fractions(official.get("fractions"))
        if overrides:
            fx.load_override_table(overrides)
            stats.sources["fractions"] = f"{PROVENANCE_OFFICIAL}:{frac_source}"
            stats.fraction_entries = fx.override_count()
        else:
            stats.sources["fractions"] = f"{PROVENANCE_COMPUTED}:exact binary ladder to 1/64"
            stats.fraction_entries = len(fx.build_reference_table())

        # -- 3. Manufacturer / brand master ----------------------------
        manufs, brands, mb_source = cls._load_manufacturer_brand(official.get("manufacturer_brand"))
        if manufs or brands:
            reg.manufacturers, reg.brands = manufs, brands
            stats.sources["manufacturer_brand"] = f"{PROVENANCE_OFFICIAL}:{mb_source}"
        elif working_rows:
            mined: MinedMasters = mine_masters(working_rows)
            reg.manufacturers, reg.brands = mined.manufacturers, mined.brands
            stats.sources["manufacturer_brand"] = (
                f"{PROVENANCE_DERIVED}:mined from {len(working_rows)} working rows"
            )
            stats.warnings.extend(mined.notes)
        else:
            stats.warnings.append(
                "no manufacturer/brand master available -- entity resolution will "
                "return UNKNOWN and route products to human review"
            )
            stats.sources["manufacturer_brand"] = "none"

        # -- 4. Brand lexicon (description mention detection) -----------
        pack = Path(pack_dir) / "brand_lexicon.json"
        if pack.exists():
            reg.brand_lexicon = BrandLexicon.from_pack(pack)
            stats.sources["brand_lexicon"] = f"{PROVENANCE_SEED}:{pack.name}"
        else:
            reg.brand_lexicon = BrandLexicon([])
            stats.sources["brand_lexicon"] = "none"
        # Teach the lexicon every brand the master knows about.
        reg.brand_lexicon.extend(
            LexiconEntry(canonical=b.name, aliases=(b.name,) + tuple(b.aliases),
                         symbol=b.symbol, provenance=b.provenance)
            for b in reg.brands
        )

        # -- 5. Taxonomy / LOV -----------------------------------------
        tax, tax_source, tax_prov = cls._load_taxonomy(official.get("lov"), Path(pack_dir))
        reg.taxonomy = tax
        stats.sources["taxonomy"] = f"{tax_prov}:{tax_source}"

        # -- 6. Content guidelines -------------------------------------
        gl = official.get("guidelines")
        if gl is not None:
            reg.guideline_blocks = loader.read_docx_blocks(gl)
            stats.sources["guidelines"] = f"{PROVENANCE_OFFICIAL}:{gl.name}"
        else:
            stats.sources["guidelines"] = "none"
            stats.warnings.append(
                "UNILOG_INTERNAL_CONTENT_GUIDELINES.docx not supplied -- description "
                "formulas are derived from the labelled delivery-format rows instead"
            )

        # -- 7. Second pass: distributor detection -----------------------
        # Brand fan-out computed from the explicit brand columns alone under-counts,
        # because co-op suppliers leave those columns as placeholders.  Re-compute it
        # using brands *mentioned in the descriptions*, which is where a co-op's true
        # brand spread is visible.
        if working_rows and reg.brand_lexicon is not None:
            reg._recompute_distributor_flags(working_rows)

        reg.reindex()
        stats.manufacturers = len(reg.manufacturers)
        stats.brands = len(reg.brands)
        stats.leaf_nodes = len(reg.taxonomy) if reg.taxonomy else 0
        stats.lov_values = reg.taxonomy.all_lov_values() if reg.taxonomy else 0
        return reg

    # ------------------------------------------------------------------
    # Official loaders (no-ops when the file is absent)
    # ------------------------------------------------------------------
    @staticmethod
    def _load_uom(path: Optional[Path]) -> Tuple[List[UomEntry], str]:
        if path is None:
            return [], ""
        book = loader.workbook_records(path) if path.suffix.lower() != ".csv" else {
            "csv": loader.csv_records(path)}
        sheet = loader.pick_sheet(book, "uom", "abbrev", "standard")
        rows = book.get(sheet or "", [])
        if not rows:
            return [], path.name
        cols = rows[0].keys()
        c_abbr = loader.find_column(cols, "abbreviation", "approved abbreviation", "uom", "symbol")
        c_type = loader.find_column(cols, "measurement type", "type", "measure", "category")
        c_term = loader.find_column(cols, "term", "unit", "name", "exact capture", "full name")
        if not c_abbr:
            return [], path.name
        by_abbr: Dict[str, UomEntry] = {}
        for r in rows:
            abbr = (r.get(c_abbr) or "").strip()
            if not abbr:
                continue
            mtype = (r.get(c_type) or "").strip() if c_type else ""
            alias = (r.get(c_term) or "").strip() if c_term else ""
            e = by_abbr.get(abbr)
            if e is None:
                by_abbr[abbr] = UomEntry(abbr, mtype, tuple(a for a in (alias,) if a))
            elif alias and alias not in e.aliases:
                by_abbr[abbr] = UomEntry(e.abbreviation, e.measurement_type,
                                         e.aliases + (alias,))
        return list(by_abbr.values()), path.name

    @staticmethod
    def _load_fractions(path: Optional[Path]) -> Tuple[Dict[str, str], str]:
        if path is None:
            return {}, ""
        book = loader.workbook_records(path) if path.suffix.lower() != ".csv" else {
            "csv": loader.csv_records(path)}
        sheet = loader.pick_sheet(book, "fraction", "decimal")
        rows = book.get(sheet or "", [])
        if not rows:
            return {}, path.name
        cols = rows[0].keys()
        c_dec = loader.find_column(cols, "decimal", "decimal value", "value")
        c_fra = loader.find_column(cols, "fraction", "fractional", "mixed")
        if not (c_dec and c_fra):
            return {}, path.name
        out: Dict[str, str] = {}
        for r in rows:
            d, f = (r.get(c_dec) or "").strip(), (r.get(c_fra) or "").strip()
            if d and f:
                out[d] = f
        return out, path.name

    @staticmethod
    def _load_manufacturer_brand(path: Optional[Path]
                                 ) -> Tuple[List[ManufacturerRecord], List[BrandRecord], str]:
        if path is None:
            return [], [], ""
        book = loader.workbook_records(path) if path.suffix.lower() != ".csv" else {
            "csv": loader.csv_records(path)}
        sheet = loader.pick_sheet(book, "manufacturer", "brand", "unicat")
        rows = book.get(sheet or "", [])
        if not rows:
            return [], [], path.name
        cols = rows[0].keys()
        c_mn = loader.find_column(cols, "MANUFACTURER_NAME", "manufacturer name", "manufacturer")
        c_mc = loader.find_column(cols, "MANUFACTURER_CODE", "manufacturer code", "mfr code")
        c_bn = loader.find_column(cols, "BRAND_NAME", "brand name", "brand")
        c_bc = loader.find_column(cols, "BRAND_CODE", "brand code")

        manufs: Dict[str, ManufacturerRecord] = {}
        brands: Dict[str, BrandRecord] = {}
        for r in rows:
            mn = (r.get(c_mn) or "").strip() if c_mn else ""
            mc = (r.get(c_mc) or "").strip() if c_mc else ""
            bn = (r.get(c_bn) or "").strip() if c_bn else ""
            bc = (r.get(c_bc) or "").strip() if c_bc else ""
            if mn:
                k = match_key(mn)
                if k not in manufs:
                    manufs[k] = ManufacturerRecord(mn, mc or None,
                                                   provenance=PROVENANCE_OFFICIAL,
                                                   source=path.name)
            if bn:
                k = match_key(bn)
                rec = brands.get(k)
                if rec is None:
                    brands[k] = BrandRecord(bn, bc or None, manufacturers=(mn,) if mn else (),
                                            provenance=PROVENANCE_OFFICIAL, source=path.name)
                elif mn and mn not in rec.manufacturers:
                    brands[k] = BrandRecord(rec.name, rec.code, rec.aliases,
                                            rec.manufacturers + (mn,), rec.provenance,
                                            rec.symbol, rec.source)
        return list(manufs.values()), list(brands.values()), path.name

    @staticmethod
    def _load_taxonomy(lov_path: Optional[Path], pack_dir: Path) -> Tuple[Taxonomy, str, str]:
        """
        Build the taxonomy from the official LOV when supplied, otherwise from the
        packaged template.  The official LOV is expected to carry one row per
        (Classpath, Attribute Label, Attribute Value); rows are grouped into leaves.
        """
        if lov_path is not None:
            book = loader.workbook_records(lov_path) if lov_path.suffix.lower() != ".csv" else {
                "csv": loader.csv_records(lov_path)}
            sheet = loader.pick_sheet(book, "lov", "vocabulary", "attribute")
            rows = book.get(sheet or "", [])
            if rows:
                cols = rows[0].keys()
                c_cp = loader.find_column(cols, "Classpath", "class path", "category path")
                c_lf = loader.find_column(cols, "Leaf Node", "leaf", "fine")
                c_al = loader.find_column(cols, "Attribute Label", "attribute")
                c_av = loader.find_column(cols, "Attribute Values", "attribute value", "value")
                c_nl = loader.find_column(cols, "Normalized Label", "normalised label")
                c_nv = loader.find_column(cols, "Normalized Values", "normalised value")
                c_fl = loader.find_column(cols, "Filtering", "filter")
                if c_cp and c_al:
                    leaves = ReferenceRegistry._leaves_from_lov(
                        rows, c_cp, c_lf, c_al, c_av, c_nl, c_nv, c_fl)
                    if leaves:
                        # Keep the packaged fallback leaf so unclassifiable rows
                        # still emit a valid 252-column record.
                        packaged = Taxonomy.from_pack(pack_dir / "taxonomy.json")
                        if packaged.fallback:
                            leaves.append(packaged.fallback)
                        return (Taxonomy(leaves, provenance=PROVENANCE_OFFICIAL),
                                lov_path.name, PROVENANCE_OFFICIAL)

        pack = pack_dir / "taxonomy.json"
        return Taxonomy.from_pack(pack), pack.name, PROVENANCE_DERIVED

    @staticmethod
    def _leaves_from_lov(rows, c_cp, c_lf, c_al, c_av, c_nl, c_nv, c_fl) -> List[LeafNode]:
        grouped: Dict[str, Dict[str, Dict[str, object]]] = {}
        for r in rows:
            cp = (r.get(c_cp) or "").strip()
            if not cp:
                continue
            label = ((r.get(c_nl) if c_nl else "") or r.get(c_al) or "").strip()
            if not label:
                continue
            value = ((r.get(c_nv) if c_nv else "") or (r.get(c_av) if c_av else "") or "").strip()
            raw_value = (r.get(c_av) or "").strip() if c_av else ""
            filtering = str(r.get(c_fl) or "").strip().lower() in ("y", "yes", "true", "1")
            attrs = grouped.setdefault(cp, {})
            slot = attrs.setdefault(label, {"values": {}, "filtering": filtering,
                                            "leaf": (r.get(c_lf) or "").strip() if c_lf else ""})
            if value:
                syns = slot["values"].setdefault(value, set())     # type: ignore[index]
                if raw_value and raw_value != value:
                    syns.add(raw_value)                            # type: ignore[union-attr]

        leaves: List[LeafNode] = []
        for cp, attrs in grouped.items():
            parts = [p.strip() for p in cp.split(">") if p.strip()]
            fine = parts[-1] if parts else ""
            leaf_attrs = tuple(
                LovAttribute(
                    label=label,
                    values=tuple(LovValue(v, tuple(sorted(s))) for v, s in slot["values"].items()),
                    filtering=bool(slot["filtering"]),
                )
                for label, slot in attrs.items()
            )
            leaves.append(LeafNode(
                id=re.sub(r"[^a-z0-9]+", "_", cp.lower()).strip("_")[:80] or "leaf",
                classpath=cp,
                dept=parts[0] if parts else "",
                klass=parts[1] if len(parts) > 1 else "",
                fine=fine,
                product_name=fine.rstrip("s") if fine else "",
                attributes=leaf_attrs,
                strong_keywords=(fine.lower(),) if fine else (),
                provenance=PROVENANCE_OFFICIAL,
                source="official LOV",
            ))
        return leaves

    def _recompute_distributor_flags(self, rows: Sequence[Dict[str, object]]) -> None:
        """Widen brand fan-out using brands named inside Part_Desc."""
        from collections import defaultdict

        from backend.normalization.text import clean_value

        fanout: Dict[str, set] = defaultdict(set)
        for row in rows:
            supplier = clean_value(row.get("Part_Manuf"))
            if not supplier:
                continue
            skey = match_key(split_name_code(supplier)[0])
            for f in ("E1_Brand", "DIB_Brand"):
                b = clean_value(row.get(f))
                if b:
                    fanout[skey].add(match_key(b))
            desc = clean_value(row.get("Part_Desc")) or ""
            for mention in self.brand_lexicon.find(desc):
                fanout[skey].add(match_key(mention.canonical))

        updated: List[ManufacturerRecord] = []
        for m in self.manufacturers:
            n = len(fanout.get(match_key(m.name), ()))
            m.brand_fanout = max(m.brand_fanout, n)
            m.is_distributor = m.brand_fanout >= DISTRIBUTOR_BRAND_FANOUT
            updated.append(m)
        self.manufacturers = updated
        n_dist = sum(1 for m in self.manufacturers if m.is_distributor)
        self.stats.warnings = [
            w for w in self.stats.warnings if "classified as distributors" not in w
        ]
        self.stats.warnings.append(
            f"{n_dist} suppliers classified as distributors/co-ops "
            f"(brand fan-out >= {DISTRIBUTOR_BRAND_FANOUT}); their Part_Manuf is not "
            f"treated as the manufacturer of record"
        )

    # ------------------------------------------------------------------
    # Indexing and lookup
    # ------------------------------------------------------------------
    def reindex(self) -> None:
        self._manuf_by_key = {}
        self._manuf_by_code = {}
        for m in self.manufacturers:
            self._manuf_by_key.setdefault(match_key(m.name), m)
            for a in m.aliases:
                self._manuf_by_key.setdefault(match_key(a), m)
            if m.code:
                self._manuf_by_code.setdefault(str(m.code).upper(), m)
        self._brand_by_key = {}
        for b in self.brands:
            self._brand_by_key.setdefault(match_key(b.name), b)
            for a in b.aliases:
                self._brand_by_key.setdefault(match_key(a), b)

    def manufacturer_by_key(self, key: str) -> Optional[ManufacturerRecord]:
        return self._manuf_by_key.get(key)

    def manufacturer_by_code(self, code: str) -> Optional[ManufacturerRecord]:
        return self._manuf_by_code.get(str(code or "").upper())

    def brand_by_key(self, key: str) -> Optional[BrandRecord]:
        return self._brand_by_key.get(key)

    @property
    def manufacturer_keys(self) -> List[str]:
        return list(self._manuf_by_key.keys())

    @property
    def brand_keys(self) -> List[str]:
        return list(self._brand_by_key.keys())

    def summary(self) -> Dict[str, object]:
        return {
            **self.stats.as_dict(),
            "taxonomy_provenance": self.taxonomy.provenance if self.taxonomy else None,
            "uom_provenance": self.uom.provenance if self.uom else None,
        }
